name: Linters (Python)

on:
  push:
    tags:
      - "*"
    branches:
      - master
  pull_request:
    branches:
      - master
defaults:
  run:
    # micromamba activation
    shell: bash -l -eo pipefail {0}

jobs:
  files-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ./environment-dev.yml
          environment-name: test_env
          micromamba-version: 2.0.2-2
      - name: Run all linters
        shell: bash -l -eo pipefail {0}
        run: |
          micromamba activate test_env
          pre-commit run --all-files --verbose --show-diff-on-failure
